import { Inter } from "next/font/google";
import "./globals.css";
import { Container, Row } from 'react-bootstrap'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container-fluid px-0">
          <div className="row">
            <div className="col">
              <nav className="navbar bg-body-tertiary">
                <div className="container-fluid">
                  <span className="navbar-brand mb-0 h1">Learning NextJS</span>
                </div>
              </nav>
            </div>
          </div>
          <div className="row">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
